#!/usr/bin/perl
use cPanelUserConfig;
use Mojolicious::Lite;
use Artemis;

our $css;

# Not found (404)
get '/missing' => sub { shift->render(template => 'does_not_exist') };

# Exception (500)
get '/dies' => sub { die 'Intentional error' };

get '/' => {text => 'Artemis API Online! '.time()};

get '/ping' => sub {
    my $c = shift;
    $c->render(json => { pong => time, user_id => $c->param('user_id') || '' });
};

post '/character' => sub {
    my $c = shift;
    $c->render(json => { board_id => Artemis->insert->board_id });
};

get '/character/:CharacterId' => sub {
    my $c = shift;
    my $character = Artemis::Character->load($c->parame('CharacterId');
    $c->render(json => { character => $character->info });
};

post '/character/:CharacterId/location/:LocationId' => sub {
    my $c = shift;
    my $character = Artemis::Entity::PlayerCharacter->load($c->param('CharacterId');
    $character->move_to($c->param('LocationId'));
    $c->render(json => { character => $character->info });
};

get '/html/page' => sub {
    my $c = shift;

    my $a = Artemis->load;
    my $character_id = $a->first_character_id($c->param('user_id'));

    my $page_id = $c->param('page_id');

    my $content = '';;
#    my $content = <<HTML;
#HTML

    my $html = join("\n", css(), $content);
    $c->render(text => $html);
};

sub fetch_params {
    my $c = shift;
    my %args;
    foreach my $key (@_) { $args{$key} = $c->param($key) }
    return %args;
}

sub css {
    $css ||= <<HTML;
<style>
\@import url('https://fonts.googleapis.com/css?family=Amarante');
\@import url('https://fonts.googleapis.com/css?family=Almendra SC');
h1 {
    font-family: 'Almendra SC';
}
p {
    font-family: 'Amarante';
    font-size: 16pt;
}
ol, ul, li {
    font-family: 'Amarante';
    font-size: 12pt;
}
</style>
HTML

}

app->start;
